export const providerEnum = {
  system: "system",
  google: "google",
};
export const genderEnum = {
  male: "male",
  female: "female",
  other : "other"
};
export const roleEnum = {
  admin: "admin",
  user: "user",
};
export const OtpTypeEnum = {
  confirmEmail: "confirm Email",
  forgetPassword: "forget Password",
};
export const industryEnum = {
  technology: "Technology",
  healthcare: "Healthcare",
  financialServices: "Financial Services",
  consumerGoods: "Consumer Goods",
  energy: "Energy",
  industrialAndManufacturing: "Industrial and Manufacturing",
  transportationAndLogistics: "Transportation and Logistics",
  mediaAndEntertainment: "Media and Entertainment",
  realEstate: "Real Estate",
  retail: "Retail",
  education: "Education",
  hospitalityAndTourism: "Hospitality and Tourism",
  agricultureAndFoodProduction: "Agriculture and Food Production",
  automotive: "Automotive",
  environmentalAndSustainability: "Environmental and Sustainability",
  professionalServices: "Professional Services",
  nonprofitAndSocialServices: "Nonprofit and Social Services",
  aerospaceAndDefense: "Aerospace and Defense",
  telecommunications: "Telecommunications",
  chemicalsAndMaterials: "Chemicals and Materials",
};
export const numberOfEmployeesEnum = {
  form1To10: "1-10",
  from11To50: "11-50",
  from51To100: "51-100",
  from101To500: "101-500",
  moreThan500: "more than 500",
};
export const jobLocEnum = {
  onsite: "Onsite",
  remote: "Remote",
  hybrid: "Hybrid",
};
export const workTime = {
  partTime: "part-time",
  fullTime: "full-time",
};
export const seniorityLevel = {
  junior: "Junior",
  midLevel: "Mid-Level",
  senior: "Senior",
  teamLead: "Team-Lead",
  cto: "CTO",
};

export const softSkillsEnum = {
  Communication: "Communication",
  Teamwork: "Teamwork",
  ProblemSolving: "ProblemSolving",
  Leadership: "Leadership",
  TimeManagement: "TimeManagement",
  Adaptability: "Adaptability",
  Creativity: "Creativity",
  CriticalThinking: "CriticalThinking",
  EmotionalIntelligence: "EmotionalIntelligence",
  ConflictResolution: "ConflictResolution",
  DecisionMaking: "DecisionMaking",
  Negotiation: "Negotiation",
  Collaboration: "Collaboration",
  PublicSpeaking: "PublicSpeaking",
  WorkEthic: "WorkEthic",
};

export const technicalSkillsEnum = {
  Programming: "Programming",
  SoftwareDevelopment: "SoftwareDevelopment",
  ArtificialIntelligence: "ArtificialIntelligence",
  MachineLearning: "MachineLearning",
  CloudComputing: "CloudComputing",
  Cybersecurity: "Cybersecurity",
  DataScience: "DataScience",
  DevOps: "DevOps",
  UI_UXDesign: "UI_UXDesign",
  Blockchain: "Blockchain",
  Telecommunications: "Telecommunications",
  MedicalCoding: "MedicalCoding",
  HealthInformatics: "HealthInformatics",
  BiomedicalEngineering: "BiomedicalEngineering",
  ClinicalResearch: "ClinicalResearch",
  Telemedicine: "Telemedicine",
  PharmaceuticalSciences: "PharmaceuticalSciences",
  FinancialModeling: "FinancialModeling",
  RiskManagement: "RiskManagement",
  Blockchain: "Blockchain",
  FintechDevelopment: "FintechDevelopment",
  DataAnalysis: "DataAnalysis",
  AlgorithmicTrading: "AlgorithmicTrading",
  ProductDesign: "ProductDesign",
  SupplyChainManagement: "SupplyChainManagement",
  QualityAssurance: "QualityAssurance",
  ManufacturingAutomation: "ManufacturingAutomation",
  PackagingDesign: "PackagingDesign",
  RenewableEnergySystems: "RenewableEnergySystems",
  EnergyStorage: "EnergyStorage",
  OilAndGasEngineering: "OilAndGasEngineering",
  NuclearEngineering: "NuclearEngineering",
  SmartGridTechnology: "SmartGridTechnology",
  MechanicalEngineering: "MechanicalEngineering",
  Robotics: "Robotics",
  IndustrialAutomation: "IndustrialAutomation",
  CAD_CAM: "CAD_CAM",
  LeanManufacturing: "LeanManufacturing",
  LogisticsOptimization: "LogisticsOptimization",
  FleetManagement: "FleetManagement",
  AutonomousVehicles: "AutonomousVehicles",
  SupplyChainAnalytics: "SupplyChainAnalytics",
  TransportationEngineering: "TransportationEngineering",
  VideoEditing: "VideoEditing",
  Animation: "Animation",
  GameDevelopment: "GameDevelopment",
  AudioEngineering: "AudioEngineering",
  DigitalMarketing: "DigitalMarketing",
  PropertyValuation: "PropertyValuation",
  RealEstateAnalytics: "RealEstateAnalytics",
  UrbanPlanning: "UrbanPlanning",
  ConstructionManagement: "ConstructionManagement",
  GISMapping: "GISMapping",
  EcommerceDevelopment: "EcommerceDevelopment",
  InventoryManagement: "InventoryManagement",
  PointOfSaleSystems: "PointOfSaleSystems",
  CustomerAnalytics: "CustomerAnalytics",
  VisualMerchandising: "VisualMerchandising",
  EdTechDevelopment: "EdTechDevelopment",
  LearningManagementSystems: "LearningManagementSystems",
  CurriculumDesign: "CurriculumDesign",
  EducationalDataAnalysis: "EducationalDataAnalysis",
  VirtualRealityInEducation: "VirtualRealityInEducation",
  HotelManagementSystems: "HotelManagementSystems",
  TravelTechnology: "TravelTechnology",
  EventPlanningSoftware: "EventPlanningSoftware",
  CustomerRelationshipManagement: "CustomerRelationshipManagement",
  RevenueManagement: "RevenueManagement",
  PrecisionAgriculture: "PrecisionAgriculture",
  FoodSafetyTechnology: "FoodSafetyTechnology",
  AgriculturalDrones: "AgriculturalDrones",
  SupplyChainOptimization: "SupplyChainOptimization",
  SustainableFarming: "SustainableFarming",
  AutomotiveDesign: "AutomotiveDesign",
  ElectricVehicleTechnology: "ElectricVehicleTechnology",
  AutonomousDrivingSystems: "AutonomousDrivingSystems",
  VehicleDynamics: "VehicleDynamics",
  ManufacturingAutomation: "ManufacturingAutomation",
  EnvironmentalImpactAssessment: "EnvironmentalImpactAssessment",
  RenewableEnergySystems: "RenewableEnergySystems",
  WasteManagementTechnology: "WasteManagementTechnology",
  CarbonFootprintAnalysis: "CarbonFootprintAnalysis",
  SustainableDesign: "SustainableDesign",
  LegalTech: "LegalTech",
  AccountingSoftware: "AccountingSoftware",
  ProjectManagementTools: "ProjectManagementTools",
  DataVisualization: "DataVisualization",
  ConsultingAnalytics: "ConsultingAnalytics",
  GrantWriting: "GrantWriting",
  SocialImpactMeasurement: "SocialImpactMeasurement",
  NonprofitManagementSoftware: "NonprofitManagementSoftware",
  CommunityOutreachTools: "CommunityOutreachTools",
  FundraisingTechnology: "FundraisingTechnology",
  AircraftDesign: "AircraftDesign",
  SpacecraftEngineering: "SpacecraftEngineering",
  DefenseSystems: "DefenseSystems",
  SatelliteTechnology: "SatelliteTechnology",
  Avionics: "Avionics",
  NetworkEngineering: "NetworkEngineering",
  WirelessCommunication: "WirelessCommunication",
  FiberOptics: "FiberOptics",
  SatelliteCommunication: "SatelliteCommunication",
  _5GTechnology: "5GTechnology",
  ChemicalEngineering: "ChemicalEngineering",
  MaterialsScience: "MaterialsScience",
  PolymerChemistry: "PolymerChemistry",
  Nanotechnology: "Nanotechnology",
  ProcessOptimization: "ProcessOptimization",
};

export const applicationStatusEnum = {
    pending : 'Pending',
    viewed : 'Viewed',
    inConsideration : 'In consideration',
    rejected : 'Rejected'
}
